### ISSUE TITLE
Ion Broken

### ISSUE THREAD

**Issue by pathfinder49** [OxfordIonTrapGroup/ion_phys#21]
@RHanley1 It seems like this commit e2afe5da47929864c2efa8670b9cdf454514a2ba broke the ion class. It fails all unittests and I can't instantiate Ion. I'll revert it on the master.

Could you please fix, test and submit a new PR.

**Comment by RHanley1** [comment]
Pull request #23 will fix this.

**Comment by hartytp** [comment]
Fixed in 2a15b504631653f286e946154b3488f0a4348159
