### ISSUE TITLE
Ion Data Citations & Accuracy

### ISSUE THREAD

**Issue by pathfinder49** [OxfordIonTrapGroup/ion_phys#35]
Currently the ion data does not cite a source. The transition frequency data for several transitions is also only approximate. 

The 850 transition in ca43 is one such example. https://github.com/OxfordIonTrapGroup/ion_phys/blob/d47a9ccce59624d371843edc5cf6928e75b832e2/ion_phys/ions/ca40.py#L54-L58

This makes ion-phys unsuitable to find the laser frequencies needed to address hyperfine transitions involging these transitions.

**Comment by hartytp** [comment]
> This makes ion-phys unsuitable to find the laser frequencies needed to address hyperfine transitions involging these transitions.

The splitting between transitions should be pretty accurate. That's usually all one wants; IIRC the splittings are small enough that the wavemeter won't generally get you there anyway. Depending on the application, you can generally use a simple diagnostic to make sure there is only one transition to reference the laser to, then set splittings using AOMs. e.g. pump to D3/2|5,+5> using sigma-pol light. Now turn on an 850 with some pi-pol light to depump and measure the depumping time constant. If you have no sigma-pol light then there is only one transition. if it has mixed polarizations there are a few, but one can still easily figure out which is which from the spectrum

**Comment by hartytp** [comment]
but, yes, PRs adding citations and better atomic structure data would be very welcome indeed
