### ISSUE TITLE
transition_filter crash

### ISSUE THREAD

**Issue by RHanley1** [OxfordIonTrapGroup/ion_phys#7]
The use of filtering in the instantiation of the ion class, for example Ca43(level_filter=[...], transition_filter=[...]) works for level_filter, but crashes for transition_filter due to disconnected level structure. I think this is because after filtering transitions, the required energy levels are not updated to reflect this (line 111 in ion_phys/common.py). 

The fix is not obvious however as there could be cases where the user puts in conflicting filtering for both level_filter and transition_filter. Should the user choose _either_ level filtering or transition filtering, but not both?

**Comment by hartytp** [comment]
Thanks for reporting. Can you post a MVCE and error message please?

**Comment by hartytp** [comment]
My motivation for keeping the transition filter separate from the level filter (although it's not that strong) is that there have been a few (albeit relatively niche) cases where it's been useful to do things like "turn D-state decay off" by removing a transition.

By "crash" do you mean "raise an exception"?

There are a few ways of addressing this and I'm not sure what's best: remove transition filter as the usefulness may not be worth the complexity and potential for confusion; improve the error messaging so users get a clear error message if they do something that won't work; in the constructor, where we do the level filtering, add an extra pass that removes any levels that don't have a transition either into or out of them.

For now, I'd lean to the first of these (remove the transition filter completely) unless someone can provide a concrete use case for it. If you agree, can you spin up a PR?

**Comment by RHanley1** [comment]
MVCE:
```from ion_phys.ions.ca43 import Ca43```
```ion = Ca43(1e-5, transition_filter = ["397", "393"])```

Error message: 

Traceback (most recent call last):
  File "test_epole.py", line 3, in <module>
    ion = Ca43(1e-5, transition_filter = ["397", "393"])
  File "c:\users\ryan_\documents\work\oxford pdra\ion_phys\ion_phys\ions\ca43.py", line 111, in __init__
    transition_filter=transition_filter)
  File "c:\users\ryan_\documents\work\oxford pdra\ion_phys\ion_phys\common.py", line 142, in __init__
    self._sort_levels()  # arrange levels in energy order
  File "c:\users\ryan_\documents\work\oxford pdra\ion_phys\ion_phys\common.py", line 276, in _sort_levels
    raise ValueError("Disconnected level structure")
ValueError: Disconnected level structure

**Comment by RHanley1** [comment]
I think having the ability to turn off transitions is useful, however this is probably more simply done by setting \Gamma = 0. In this case, all of the data structures are the same and we don't have these issues. I'll edit common.py and create a PR.

**Comment by hartytp** [comment]
Thanks.

Nitpick: GitHub syntax
- if you use triple quotes followed by the word python then it will do syntax highlighting, which makes the code more readable (you also don't need triple quotes on each line, just at the beginning and end of the block)
- I'd also use a code block for the error message to make it more readable

That makes sense: you haven't got any transitions out of the ground-level so it freaks out. 

> I think having the ability to turn off transitions is useful

I think I agree, but I can't come up with a concrete example. Do you have one in mind.

> however this is probably more simply done by setting \Gamma = 0. In this case, all of the data structures are the same and we don't have these issues. I'll edit common.py and create a PR.

That sounds like a better plan, thanks!
